version: "3.8"
services:
  nginx:
    build: ./docker/nginx
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - "./:/var/www/html"
  php:
    build: ./docker/php
    volumes:
      - "./:/var/www/html"
